name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Create Build Directory Exe
      run: mkdir _dist
      
    - name: Restore Packages
      run: nuget restore TimeTraker.sln

    - name: Build Solution
      run: |
        msbuild.exe TimeTraker.sln /nologo /nr:false
    - name: Build Solution Exe
      run: C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe /p:Configuration=Release TimeTraker.sln
        
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: TimeTrakerBundle
        path: "./_build"     
    
    -name: Upload binaries to release
     with:
       repo_token: ${{ secrets.GITHUB_TOKEN }}
       file: dist/${{ matrix.artifact_name }}
       asset_name: ${{ matrix.asset_name }}

    



        
