name: Build1
on:
  push:
    branches: main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Binary
        shell: cmd
        run: call .\Build.cmd
    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: C:\Windows\Microsoft.NET\Framework\v4.7.2\csc.exe /nologo Program.cs
    - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/${{ matrix.artifact_name }}
                  asset_name: ${{ matrix.asset_name }}
                  tag: ${{ github.ref }}
        
